In [3]:
import pickle
import numpy as np
import os

In [5]:
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/train', 'graphs.pkl'), 'rb') as f:
    train_adjs = pickle.load(f)
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/train', 'properties.pkl'), 'rb') as f:
    train_properties = pickle.load(f)
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/train', 'descriptions.pkl'), 'rb') as f:
    train_desc = pickle.load(f)

with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/test', 'graphs.pkl'), 'rb') as f:
    test_adjs = pickle.load(f)
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/test', 'properties.pkl'), 'rb') as f:
    test_properties = pickle.load(f)
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/test', 'descriptions.pkl'), 'rb') as f:
    test_desc = pickle.load(f)

with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/val', 'graphs.pkl'), 'rb') as f:
    val_adjs = pickle.load(f)
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/val', 'properties.pkl'), 'rb') as f:
    val_properties = pickle.load(f)
with open(os.path.join('../datasets/NWPU-Captions/NWPU_Graphs/val', 'descriptions.pkl'), 'rb') as f:
    val_desc = pickle.load(f)

In [6]:
train_adjs

[array([[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 arr

In [7]:
train_desc

['Two larger planes and a smaller plane parked on the open area .',
 'Two larger airplanes and one smaller airplane are parked at the airport .',
 'Two airplanes and one smaller plane were parked in the open space .',
 'Three airplanes are parked on the open place .',
 'There are three planes on the ground .',
 'Some different kinds of planes parked on the airport and some roundabouts and white buildings beside  . ',
 'Here are five white planes and one blue plane .',
 'Six planes were neatly arranged on the airport beside the building .',
 'There are many airplanes parked beside the airport by the runway .',
 'There is an oval lawn around the six planes .',
 'A white plane with the red mark parked on the open area .',
 'An airplane with red lines docked on the runway .',
 'An airplane with a red pattern was parked in the open space .',
 'There is a white plane on the runway .',
 'An airplane is on wired ground divided into equal areas .',
 'Four planes parked on the airport and a park